runtime: java11

instance_class: F2

env_variables:
  BUCKET_NAME: "doancuoikycloud2023"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
